Changes to MRI resources
nimh-sfim/lab-docs pull request #53
Opened 2021-08-11 18:31 UTC by Micahh222

2021-08-11 19:08 UTC, handwerkerd requested changes
Good additions. Just remove the link to the Huettel pdf.

2021-08-11 19:08 UTC, handwerkerd commented on mri.md
> +## Books available by hardback or pdf
```suggestion
## Books (ask lab members for copies)
```

2021-08-11 19:08 UTC, handwerkerd commented on mri.md
> +[huettel_pdf]: https://github.com/Micahh222/lab-docs/files/6970668/fMRI_Huettel.pdf
```suggestion
```

2021-08-11 19:08 UTC, handwerkerd commented on mri.md
> +- [Functional Magnetic Resonance Imaging by Huettel, Song, & McCarthy (designed for undergrad introductory courses)][huettel_pdf]
We shouldn't be sharing pdfs of a copyrighted book on our lab website.

2021-08-12 18:04 UTC, handwerkerd approved these changes

2021-08-12 19:21 UTC, Micahh222 commented
@jbteves

2021-08-12 19:43 UTC, jbteves approved these changes

2021-08-12 19:44 UTC, jbteves commented
One note: when opening a pull request, if you make an initial comment like
```
Closes #123
```
Then when the pull request is merged, that issue will automagically be closed.

2021-08-12 19:44 UTC, merged

2021-08-12 20:21 UTC, Micahh222 commented
Thank you Josh :)

On Thu, Aug 12, 2021, 3:44 PM Joshua Teves ***@***.***> wrote:

> Merged #53 <https://github.com/nimh-sfim/lab-docs/pull/53> into main.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nimh-sfim/lab-docs/pull/53#event-5151780329>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AN7YJCUVWTWPNN2OQC6XGS3T4QQDPANCNFSM5B7FTKRA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>